[package]
name = "webserver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.148"
rocket = {version ="0.5.0-rc.1", features=["json"]}
base64 = "0.13.1"
image = "0.24.5"