version: "3"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"
    command: npm run dev -- --host
#    links:
#      - app  # up the backend before frontend

  app:
    build: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/app
#    command: cargo run  # run the app with reload on code change (cargo-watch installed in app/Dockerfile)
    command: cargo watch -x run  # run the app with reload on code change (cargo-watch installed in app/Dockerfile)
#    links:
#      - db
    # diesel infer_schema macro gives warnings with this flag.
    # environment:
    #   - CARGO_INCREMENTAL=1
#    command: bash -c "bash ./wait-for-it.sh db:5432 -q -- diesel setup && cargo watch -x run"

#  db:
#    image: "postgres:9"
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data/pgdata
#    environment:
#      POSTGRES_PASSWORD: supersecretpassword
#      PGDATA: /var/lib/postgresql/data/pgdata

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
